version: '3.8'

services:
  testing-gui:
    build: .
    container_name: standardized-testing-gui
    environment:
      - DISPLAY=host.docker.internal:0.0
      - PYTHONPATH=/app
    volumes:
      # Mount local data directory for persistent storage
      - ./data:/app/user_data
      # Mount logs directory
      - ./logs:/app/logs
      # Mount resources directory (in case of updates)
      - ./resources:/app/resources:ro
    networks:
      - testing-gui-network
    stdin_open: true
    tty: true
    # For Windows with WSL2 Docker Desktop
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Optional: Add a web interface service for future use
  web-interface:
    build: .
    container_name: testing-gui-web
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./data:/app/user_data
    networks:
      - testing-gui-network
    profiles:
      - web
    command: python web_interface.py  # Future web interface

networks:
  testing-gui-network:
    driver: bridge

volumes:
  testing-data:
    driver: local